### ISSUE TITLE
Godot 3.2 support

### ISSUE THREAD

**Issue by dark-penguin** [yumedev40/Yume-Visual-Novel-Editor#17] opened 2020-01-26 19:01 UTC
I've tried following the steps in the YouTube video, but it seems like those are incomplete.

- Trying to save the scene gives a message "A root node is required to save the scene"
- Clicking the "Preview" button changes it into "Pause" and "Stop" buttons, and the spinner next to it starts spinning, but nothing else happens
- Trying to run the project says that there is no default scene assigned; indeed, I have not assigned any, because I don't know which one to assign - maybe this is the problem?..
- The built-in "Play Scene" button launches the editor (in a separate window) and not the project

I think I'm doing something wrong. :)

**Comment by yumedev40** [comment] 2020-01-26 23:34
@dark-penguin

My apologies for the plugin giving you a hard time.

Because the editor is still in early alpha and the workflow is liable to sudden and drastic changes, any tutorials may become out of date rather quickly.

I'll try to help you get it running (screenshots of what you are seeing may help figure out what is going wrong).

- That first message "A root node is required to save the scene" is from the Godot editor asking you to open a scene before ctrl+s will work as a shortcut.  If you do not have any scene tabs open in Godot, you will need to use the **_Save Project_** option in the **File** menu dropdown at the top of the **_Yume plugin editor_** to save the project.

- The wiki section of this repository contains a section called _Workflow WIP_ : https://github.com/yumedev40/Yume-Visual-Novel-Editor/wiki/Workflow---WIP

- - The getting started section may be useful too : 
https://github.com/yumedev40/Yume-Visual-Novel-Editor/wiki/Initial-setup

Some things have been changed a little, but it should still work with the current build of the editor.  Try using a Fade Screen action with the color set to something other than black to see if there are any visual changes in the preview.

Please let me know if you encounter any further issues using the editor.  Screenshots of your setup, as well as any warning and error messages that may popup would help narrow down the causes of these issues.

**Comment by dark-penguin** [comment] 2020-01-27 00:14
WIP workflow is fine - I wanted to see if I can contribute something, but first I have to figure out how it works... and for that, it has to actually work. :)

I choose a folder, enter a name and click "Create project". The preview window is grey, and not black or white as I see in the examples. Also, at this step I see three error messages in "Output":
```
res://addons/Yume_VisualNovelEditor/Editor/Yume_VN_Editor.gd:409 - Trying to assign value of type 'Node' to a variable of type 'GDScript'.
res://addons/Yume_VisualNovelEditor/Editor/Editor_Component_Scripts/scene_preview.gd:63 - Invalid get index 'game_scene' (on base: 'Dictionary').
res://addons/Yume_VisualNovelEditor/Editor/Editor_Component_Scripts/scene_preview.gd:63 - Invalid get index 'game_scene' (on base: 'Dictionary').
```
I create a chapter and a scene, name them, double-click that scene - it turns green, "Output" says that a scene is opened. I drag "Fade", it appears as it should.

I click "File" - "Save project". No confirmation window or anything, but "Output" gives more errors:
```
File must be opened before use.
File must be opened before use.
File must be opened before use.
res://addons/Yume_VisualNovelEditor/Editor/Yume_VN_Editor.gd:557 - Invalid get index 'main_menu' (on base: 'Dictionary').
Visual Novel Project  saved
```
Now, clicking "Preview" does nothing except it changes into "Stop preview" and the spinner spins. If I click "Stop preview", "Output" gives more errors:
```
res://addons/Yume_VisualNovelEditor/Editor/Editor_Component_Scripts/scene_preview.gd:161 - Invalid call. Nonexistent function '_reset' in base 'Nil'.
```
Trying to "Play project" shows a window "No main scene has ever been defined, select one?".

If I press "Ctrl+S", it says "Saved 1 modified resource".
If I press "Ctrl+S" again, it says "A root node is required to save the scene". (Ah, so it happens when there is nothing to save...)

Oh... OK, I've figured it out. You're on Godot 3.1 . I've just switched to 3.2-master. :) On 3.1, it works. Now I can start hacking and looking at whatever else is not working properly. You might want to note somewhere that 3.2 is not supported yet - it's almost out, I would expect people to start switching soon.

**Comment by yumedev40** [comment] 2020-01-27 01:28
@dark-penguin 

There were a few files I missed when updating the master branch last week that fixed the errors in 3.2

I've updated the files in the v0.2.0 branch to reflect the current state of the editor.  It should also work with the 3.2 master branch of Godot (I'm working on it using Godot 3.2 rc3).

**Comment by dark-penguin** [comment] 2020-01-27 01:41
OK, it works on 0.2.0 branch !

**Comment by yumedev40** [comment] 2020-01-27 01:50
Thank you for your help.

I made a note on the master branch readme about Godot version requirements.

I'm closing this issue for now, but will reopen it if anyone encounters compatibility problems with v0.2.0 and Godot 3.2 in the future.

**Closed as completed by yumedev40** 2020-01-27 01:50 UTC
Labels: bug
